.TH ARCHIVE_READ_ADD_PASSPHRASE 3 "September 14, 2014" ""
.SH NAME
.ad l
\fB\%archive_read_add_passphrase\fP,
\fB\%archive_read_set_passphrase_callback\fP
\- functions for reading encrypted archives
.SH LIBRARY
.ad l
Streaming Archive Library (libarchive, -larchive)
.SH SYNOPSIS
.ad l
\fB#include <archive.h>\fP
.br
\fIint\fP
.br
\fB\%archive_read_add_passphrase\fP(\fI\%struct\ archive\ *\fP, \fI\%const\ char\ *passphrase\fP);
.br
\fIint\fP
.br
\fB\%archive_read_set_passphrase_callback\fP(\fI\%struct\ archive\ *\fP, \fI\%void\ *client_data\fP, \fI\%archive_passphrase_callback\ *\fP);
.SH DESCRIPTION
.ad l
.RS 5
.TP
\fB\%archive_read_add_passphrase\fP()
Register passphrases for reading an encryption archive.
If
\fIpassphrase\fP
is
.BR NULL
or empty, this function will do nothing and
\fBARCHIVE_FAILED\fP
will be returned.
Otherwise,
\fBARCHIVE_OK\fP
will be returned.
.TP
\fB\%archive_read_set_passphrase_callback\fP()
Register a callback function that will be invoked to get a passphrase 
for decryption after trying all the passphrases registered by the
\fB\%archive_read_add_passphrase\fP()
function failed.
.RE
.SH SEE ALSO
.ad l
\fBtar\fP(1),
\fBarchive_read\fP(3),
\fBarchive_read_set_options\fP(3),
\fBlibarchive\fP(3)
