.TH ARCHIVE_WRITE_FINISH_ENTRY 3 "February 28, 2017" ""
.SH NAME
.ad l
\fB\%archive_write_finish_entry\fP
\- functions for creating archives
.SH LIBRARY
.ad l
Streaming Archive Library (libarchive, -larchive)
.SH SYNOPSIS
.ad l
\fB#include <archive.h>\fP
.br
\fIint\fP
.br
\fB\%archive_write_finish_entry\fP(\fI\%struct\ archive\ *\fP);
.SH DESCRIPTION
.ad l
Close out the entry just written.
In particular, this writes out the final padding required by some formats.
Ordinarily, clients never need to call this, as it
is called automatically by
\fB\%archive_write_header\fP()
and
\fB\%archive_write_close\fP()
as needed.
For
Tn archive_write_disk
handles, this flushes pending file attribute changes like modification time.
.SH RETURN VALUES
.ad l
This function returns
\fBARCHIVE_OK\fP
on success, or one of several non-zero
error codes for errors.
Specific error codes include:
\fBARCHIVE_RETRY\fP
for operations that might succeed if retried,
\fBARCHIVE_WARN\fP
for unusual conditions that do not prevent further operations, and
\fBARCHIVE_FATAL\fP
for serious errors that make remaining operations impossible.
.SH ERRORS
.ad l
Detailed error codes and textual descriptions are available from the
\fB\%archive_errno\fP()
and
\fB\%archive_error_string\fP()
functions.
.SH SEE ALSO
.ad l
\fBtar\fP(1),
\fBarchive_write_data\fP(3),
\fBarchive_write_set_options\fP(3),
\fBlibarchive\fP(3),
\fBcpio\fP(5),
\fBmtree\fP(5),
\fBtar\fP(5)
