.TH ARCHIVE_READ_NEW 3 "February 2, 2012" ""
.SH NAME
.ad l
\fB\%archive_read_new\fP
\- functions for reading streaming archives
.SH LIBRARY
.ad l
Streaming Archive Library (libarchive, -larchive)
.SH SYNOPSIS
.ad l
\fB#include <archive.h>\fP
.br
\fIstruct archive *\fP
.br
\fB\%archive_read_new\fP(\fI\%void\fP);
.SH DESCRIPTION
.ad l
Allocates and initializes a
Tn struct archive
object suitable for reading from an archive.
.BR NULL
is returned on error.
.PP
A complete description of the
Tn struct archive
object can be found in the overview manual page for
\fBlibarchive\fP(3).
.SH SEE ALSO
.ad l
\fBtar\fP(1),
\fBarchive_read_data\fP(3),
\fBarchive_read_filter\fP(3),
\fBarchive_read_format\fP(3),
\fBarchive_read_set_options\fP(3),
\fBarchive_util\fP(3),
\fBlibarchive\fP(3),
\fBtar\fP(5)
