
default: all


archive_entry.3: ../mdoc2man.awk ../../libarchive/archive_entry.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_entry.3 > archive_entry.3

archive_entry_acl.3: ../mdoc2man.awk ../../libarchive/archive_entry_acl.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_entry_acl.3 > archive_entry_acl.3

archive_entry_linkify.3: ../mdoc2man.awk ../../libarchive/archive_entry_linkify.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_entry_linkify.3 > archive_entry_linkify.3

archive_entry_misc.3: ../mdoc2man.awk ../../libarchive/archive_entry_misc.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_entry_misc.3 > archive_entry_misc.3

archive_entry_paths.3: ../mdoc2man.awk ../../libarchive/archive_entry_paths.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_entry_paths.3 > archive_entry_paths.3

archive_entry_perms.3: ../mdoc2man.awk ../../libarchive/archive_entry_perms.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_entry_perms.3 > archive_entry_perms.3

archive_entry_stat.3: ../mdoc2man.awk ../../libarchive/archive_entry_stat.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_entry_stat.3 > archive_entry_stat.3

archive_entry_time.3: ../mdoc2man.awk ../../libarchive/archive_entry_time.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_entry_time.3 > archive_entry_time.3

archive_read.3: ../mdoc2man.awk ../../libarchive/archive_read.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read.3 > archive_read.3

archive_read_add_passphrase.3: ../mdoc2man.awk ../../libarchive/archive_read_add_passphrase.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_add_passphrase.3 > archive_read_add_passphrase.3

archive_read_data.3: ../mdoc2man.awk ../../libarchive/archive_read_data.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_data.3 > archive_read_data.3

archive_read_disk.3: ../mdoc2man.awk ../../libarchive/archive_read_disk.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_disk.3 > archive_read_disk.3

archive_read_extract.3: ../mdoc2man.awk ../../libarchive/archive_read_extract.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_extract.3 > archive_read_extract.3

archive_read_filter.3: ../mdoc2man.awk ../../libarchive/archive_read_filter.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_filter.3 > archive_read_filter.3

archive_read_format.3: ../mdoc2man.awk ../../libarchive/archive_read_format.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_format.3 > archive_read_format.3

archive_read_free.3: ../mdoc2man.awk ../../libarchive/archive_read_free.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_free.3 > archive_read_free.3

archive_read_header.3: ../mdoc2man.awk ../../libarchive/archive_read_header.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_header.3 > archive_read_header.3

archive_read_new.3: ../mdoc2man.awk ../../libarchive/archive_read_new.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_new.3 > archive_read_new.3

archive_read_open.3: ../mdoc2man.awk ../../libarchive/archive_read_open.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_open.3 > archive_read_open.3

archive_read_set_options.3: ../mdoc2man.awk ../../libarchive/archive_read_set_options.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_read_set_options.3 > archive_read_set_options.3

archive_util.3: ../mdoc2man.awk ../../libarchive/archive_util.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_util.3 > archive_util.3

archive_write.3: ../mdoc2man.awk ../../libarchive/archive_write.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write.3 > archive_write.3

archive_write_blocksize.3: ../mdoc2man.awk ../../libarchive/archive_write_blocksize.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_blocksize.3 > archive_write_blocksize.3

archive_write_data.3: ../mdoc2man.awk ../../libarchive/archive_write_data.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_data.3 > archive_write_data.3

archive_write_disk.3: ../mdoc2man.awk ../../libarchive/archive_write_disk.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_disk.3 > archive_write_disk.3

archive_write_filter.3: ../mdoc2man.awk ../../libarchive/archive_write_filter.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_filter.3 > archive_write_filter.3

archive_write_finish_entry.3: ../mdoc2man.awk ../../libarchive/archive_write_finish_entry.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_finish_entry.3 > archive_write_finish_entry.3

archive_write_format.3: ../mdoc2man.awk ../../libarchive/archive_write_format.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_format.3 > archive_write_format.3

archive_write_free.3: ../mdoc2man.awk ../../libarchive/archive_write_free.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_free.3 > archive_write_free.3

archive_write_header.3: ../mdoc2man.awk ../../libarchive/archive_write_header.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_header.3 > archive_write_header.3

archive_write_new.3: ../mdoc2man.awk ../../libarchive/archive_write_new.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_new.3 > archive_write_new.3

archive_write_open.3: ../mdoc2man.awk ../../libarchive/archive_write_open.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_open.3 > archive_write_open.3

archive_write_set_options.3: ../mdoc2man.awk ../../libarchive/archive_write_set_options.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_set_options.3 > archive_write_set_options.3

archive_write_set_passphrase.3: ../mdoc2man.awk ../../libarchive/archive_write_set_passphrase.3
	awk -f ../mdoc2man.awk < ../../libarchive/archive_write_set_passphrase.3 > archive_write_set_passphrase.3

cpio.5: ../mdoc2man.awk ../../libarchive/cpio.5
	awk -f ../mdoc2man.awk < ../../libarchive/cpio.5 > cpio.5

libarchive-formats.5: ../mdoc2man.awk ../../libarchive/libarchive-formats.5
	awk -f ../mdoc2man.awk < ../../libarchive/libarchive-formats.5 > libarchive-formats.5

libarchive.3: ../mdoc2man.awk ../../libarchive/libarchive.3
	awk -f ../mdoc2man.awk < ../../libarchive/libarchive.3 > libarchive.3

libarchive_changes.3: ../mdoc2man.awk ../../libarchive/libarchive_changes.3
	awk -f ../mdoc2man.awk < ../../libarchive/libarchive_changes.3 > libarchive_changes.3

libarchive_internals.3: ../mdoc2man.awk ../../libarchive/libarchive_internals.3
	awk -f ../mdoc2man.awk < ../../libarchive/libarchive_internals.3 > libarchive_internals.3

mtree.5: ../mdoc2man.awk ../../libarchive/mtree.5
	awk -f ../mdoc2man.awk < ../../libarchive/mtree.5 > mtree.5

tar.5: ../mdoc2man.awk ../../libarchive/tar.5
	awk -f ../mdoc2man.awk < ../../libarchive/tar.5 > tar.5

bsdtar.1: ../mdoc2man.awk ../../tar/bsdtar.1
	awk -f ../mdoc2man.awk < ../../tar/bsdtar.1 > bsdtar.1

bsdcpio.1: ../mdoc2man.awk ../../cpio/bsdcpio.1
	awk -f ../mdoc2man.awk < ../../cpio/bsdcpio.1 > bsdcpio.1
all: archive_entry.3 archive_entry_acl.3 archive_entry_linkify.3 archive_entry_misc.3 archive_entry_paths.3 archive_entry_perms.3 archive_entry_stat.3 archive_entry_time.3 archive_read.3 archive_read_add_passphrase.3 archive_read_data.3 archive_read_disk.3 archive_read_extract.3 archive_read_filter.3 archive_read_format.3 archive_read_free.3 archive_read_header.3 archive_read_new.3 archive_read_open.3 archive_read_set_options.3 archive_util.3 archive_write.3 archive_write_blocksize.3 archive_write_data.3 archive_write_disk.3 archive_write_filter.3 archive_write_finish_entry.3 archive_write_format.3 archive_write_free.3 archive_write_header.3 archive_write_new.3 archive_write_open.3 archive_write_set_options.3 archive_write_set_passphrase.3 cpio.5 libarchive-formats.5 libarchive.3 libarchive_changes.3 libarchive_internals.3 mtree.5 tar.5 bsdtar.1 bsdcpio.1
