# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
- name: "Translation"
  color: "9FABF9"
  description: "Issues or pull requests related to translation"

Translation:
- changed-files:
  - any-glob-to-any-file: 'src/i18n/*'
