# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mircea/work/rpi-imager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mircea/work/rpi-imager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mircea/work/rpi-imager/CMakeFiles /home/mircea/work/rpi-imager/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mircea/work/rpi-imager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rpi-imager

# Build rule for target.
rpi-imager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpi-imager
.PHONY : rpi-imager

# fast build rule for target.
rpi-imager/fast:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/build
.PHONY : rpi-imager/fast

#=============================================================================
# Target rules for targets named rpi-imager_autogen

# Build rule for target.
rpi-imager_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpi-imager_autogen
.PHONY : rpi-imager_autogen

# fast build rule for target.
rpi-imager_autogen/fast:
	$(MAKE) -f CMakeFiles/rpi-imager_autogen.dir/build.make CMakeFiles/rpi-imager_autogen.dir/build
.PHONY : rpi-imager_autogen/fast

acceleratedcryptographichash.o: acceleratedcryptographichash.cpp.o

.PHONY : acceleratedcryptographichash.o

# target to build an object file
acceleratedcryptographichash.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/acceleratedcryptographichash.cpp.o
.PHONY : acceleratedcryptographichash.cpp.o

acceleratedcryptographichash.i: acceleratedcryptographichash.cpp.i

.PHONY : acceleratedcryptographichash.i

# target to preprocess a source file
acceleratedcryptographichash.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/acceleratedcryptographichash.cpp.i
.PHONY : acceleratedcryptographichash.cpp.i

acceleratedcryptographichash.s: acceleratedcryptographichash.cpp.s

.PHONY : acceleratedcryptographichash.s

# target to generate assembly for a file
acceleratedcryptographichash.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/acceleratedcryptographichash.cpp.s
.PHONY : acceleratedcryptographichash.cpp.s

dependencies/mountutils/src/linux/functions.o: dependencies/mountutils/src/linux/functions.cpp.o

.PHONY : dependencies/mountutils/src/linux/functions.o

# target to build an object file
dependencies/mountutils/src/linux/functions.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/dependencies/mountutils/src/linux/functions.cpp.o
.PHONY : dependencies/mountutils/src/linux/functions.cpp.o

dependencies/mountutils/src/linux/functions.i: dependencies/mountutils/src/linux/functions.cpp.i

.PHONY : dependencies/mountutils/src/linux/functions.i

# target to preprocess a source file
dependencies/mountutils/src/linux/functions.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/dependencies/mountutils/src/linux/functions.cpp.i
.PHONY : dependencies/mountutils/src/linux/functions.cpp.i

dependencies/mountutils/src/linux/functions.s: dependencies/mountutils/src/linux/functions.cpp.s

.PHONY : dependencies/mountutils/src/linux/functions.s

# target to generate assembly for a file
dependencies/mountutils/src/linux/functions.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/dependencies/mountutils/src/linux/functions.cpp.s
.PHONY : dependencies/mountutils/src/linux/functions.cpp.s

dependencies/sha256crypt/sha256crypt.o: dependencies/sha256crypt/sha256crypt.c.o

.PHONY : dependencies/sha256crypt/sha256crypt.o

# target to build an object file
dependencies/sha256crypt/sha256crypt.c.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/dependencies/sha256crypt/sha256crypt.c.o
.PHONY : dependencies/sha256crypt/sha256crypt.c.o

dependencies/sha256crypt/sha256crypt.i: dependencies/sha256crypt/sha256crypt.c.i

.PHONY : dependencies/sha256crypt/sha256crypt.i

# target to preprocess a source file
dependencies/sha256crypt/sha256crypt.c.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/dependencies/sha256crypt/sha256crypt.c.i
.PHONY : dependencies/sha256crypt/sha256crypt.c.i

dependencies/sha256crypt/sha256crypt.s: dependencies/sha256crypt/sha256crypt.c.s

.PHONY : dependencies/sha256crypt/sha256crypt.s

# target to generate assembly for a file
dependencies/sha256crypt/sha256crypt.c.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/dependencies/sha256crypt/sha256crypt.c.s
.PHONY : dependencies/sha256crypt/sha256crypt.c.s

downloadextractthread.o: downloadextractthread.cpp.o

.PHONY : downloadextractthread.o

# target to build an object file
downloadextractthread.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadextractthread.cpp.o
.PHONY : downloadextractthread.cpp.o

downloadextractthread.i: downloadextractthread.cpp.i

.PHONY : downloadextractthread.i

# target to preprocess a source file
downloadextractthread.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadextractthread.cpp.i
.PHONY : downloadextractthread.cpp.i

downloadextractthread.s: downloadextractthread.cpp.s

.PHONY : downloadextractthread.s

# target to generate assembly for a file
downloadextractthread.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadextractthread.cpp.s
.PHONY : downloadextractthread.cpp.s

downloadstatstelemetry.o: downloadstatstelemetry.cpp.o

.PHONY : downloadstatstelemetry.o

# target to build an object file
downloadstatstelemetry.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadstatstelemetry.cpp.o
.PHONY : downloadstatstelemetry.cpp.o

downloadstatstelemetry.i: downloadstatstelemetry.cpp.i

.PHONY : downloadstatstelemetry.i

# target to preprocess a source file
downloadstatstelemetry.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadstatstelemetry.cpp.i
.PHONY : downloadstatstelemetry.cpp.i

downloadstatstelemetry.s: downloadstatstelemetry.cpp.s

.PHONY : downloadstatstelemetry.s

# target to generate assembly for a file
downloadstatstelemetry.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadstatstelemetry.cpp.s
.PHONY : downloadstatstelemetry.cpp.s

downloadthread.o: downloadthread.cpp.o

.PHONY : downloadthread.o

# target to build an object file
downloadthread.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadthread.cpp.o
.PHONY : downloadthread.cpp.o

downloadthread.i: downloadthread.cpp.i

.PHONY : downloadthread.i

# target to preprocess a source file
downloadthread.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadthread.cpp.i
.PHONY : downloadthread.cpp.i

downloadthread.s: downloadthread.cpp.s

.PHONY : downloadthread.s

# target to generate assembly for a file
downloadthread.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/downloadthread.cpp.s
.PHONY : downloadthread.cpp.s

driveformatthread.o: driveformatthread.cpp.o

.PHONY : driveformatthread.o

# target to build an object file
driveformatthread.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/driveformatthread.cpp.o
.PHONY : driveformatthread.cpp.o

driveformatthread.i: driveformatthread.cpp.i

.PHONY : driveformatthread.i

# target to preprocess a source file
driveformatthread.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/driveformatthread.cpp.i
.PHONY : driveformatthread.cpp.i

driveformatthread.s: driveformatthread.cpp.s

.PHONY : driveformatthread.s

# target to generate assembly for a file
driveformatthread.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/driveformatthread.cpp.s
.PHONY : driveformatthread.cpp.s

drivelistitem.o: drivelistitem.cpp.o

.PHONY : drivelistitem.o

# target to build an object file
drivelistitem.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistitem.cpp.o
.PHONY : drivelistitem.cpp.o

drivelistitem.i: drivelistitem.cpp.i

.PHONY : drivelistitem.i

# target to preprocess a source file
drivelistitem.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistitem.cpp.i
.PHONY : drivelistitem.cpp.i

drivelistitem.s: drivelistitem.cpp.s

.PHONY : drivelistitem.s

# target to generate assembly for a file
drivelistitem.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistitem.cpp.s
.PHONY : drivelistitem.cpp.s

drivelistmodel.o: drivelistmodel.cpp.o

.PHONY : drivelistmodel.o

# target to build an object file
drivelistmodel.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistmodel.cpp.o
.PHONY : drivelistmodel.cpp.o

drivelistmodel.i: drivelistmodel.cpp.i

.PHONY : drivelistmodel.i

# target to preprocess a source file
drivelistmodel.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistmodel.cpp.i
.PHONY : drivelistmodel.cpp.i

drivelistmodel.s: drivelistmodel.cpp.s

.PHONY : drivelistmodel.s

# target to generate assembly for a file
drivelistmodel.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistmodel.cpp.s
.PHONY : drivelistmodel.cpp.s

drivelistmodelpollthread.o: drivelistmodelpollthread.cpp.o

.PHONY : drivelistmodelpollthread.o

# target to build an object file
drivelistmodelpollthread.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistmodelpollthread.cpp.o
.PHONY : drivelistmodelpollthread.cpp.o

drivelistmodelpollthread.i: drivelistmodelpollthread.cpp.i

.PHONY : drivelistmodelpollthread.i

# target to preprocess a source file
drivelistmodelpollthread.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistmodelpollthread.cpp.i
.PHONY : drivelistmodelpollthread.cpp.i

drivelistmodelpollthread.s: drivelistmodelpollthread.cpp.s

.PHONY : drivelistmodelpollthread.s

# target to generate assembly for a file
drivelistmodelpollthread.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/drivelistmodelpollthread.cpp.s
.PHONY : drivelistmodelpollthread.cpp.s

imagewriter.o: imagewriter.cpp.o

.PHONY : imagewriter.o

# target to build an object file
imagewriter.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/imagewriter.cpp.o
.PHONY : imagewriter.cpp.o

imagewriter.i: imagewriter.cpp.i

.PHONY : imagewriter.i

# target to preprocess a source file
imagewriter.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/imagewriter.cpp.i
.PHONY : imagewriter.cpp.i

imagewriter.s: imagewriter.cpp.s

.PHONY : imagewriter.s

# target to generate assembly for a file
imagewriter.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/imagewriter.cpp.s
.PHONY : imagewriter.cpp.s

linux/linuxdrivelist.o: linux/linuxdrivelist.cpp.o

.PHONY : linux/linuxdrivelist.o

# target to build an object file
linux/linuxdrivelist.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/linux/linuxdrivelist.cpp.o
.PHONY : linux/linuxdrivelist.cpp.o

linux/linuxdrivelist.i: linux/linuxdrivelist.cpp.i

.PHONY : linux/linuxdrivelist.i

# target to preprocess a source file
linux/linuxdrivelist.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/linux/linuxdrivelist.cpp.i
.PHONY : linux/linuxdrivelist.cpp.i

linux/linuxdrivelist.s: linux/linuxdrivelist.cpp.s

.PHONY : linux/linuxdrivelist.s

# target to generate assembly for a file
linux/linuxdrivelist.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/linux/linuxdrivelist.cpp.s
.PHONY : linux/linuxdrivelist.cpp.s

linux/udisks2api.o: linux/udisks2api.cpp.o

.PHONY : linux/udisks2api.o

# target to build an object file
linux/udisks2api.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/linux/udisks2api.cpp.o
.PHONY : linux/udisks2api.cpp.o

linux/udisks2api.i: linux/udisks2api.cpp.i

.PHONY : linux/udisks2api.i

# target to preprocess a source file
linux/udisks2api.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/linux/udisks2api.cpp.i
.PHONY : linux/udisks2api.cpp.i

linux/udisks2api.s: linux/udisks2api.cpp.s

.PHONY : linux/udisks2api.s

# target to generate assembly for a file
linux/udisks2api.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/linux/udisks2api.cpp.s
.PHONY : linux/udisks2api.cpp.s

localfileextractthread.o: localfileextractthread.cpp.o

.PHONY : localfileextractthread.o

# target to build an object file
localfileextractthread.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/localfileextractthread.cpp.o
.PHONY : localfileextractthread.cpp.o

localfileextractthread.i: localfileextractthread.cpp.i

.PHONY : localfileextractthread.i

# target to preprocess a source file
localfileextractthread.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/localfileextractthread.cpp.i
.PHONY : localfileextractthread.cpp.i

localfileextractthread.s: localfileextractthread.cpp.s

.PHONY : localfileextractthread.s

# target to generate assembly for a file
localfileextractthread.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/localfileextractthread.cpp.s
.PHONY : localfileextractthread.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/main.cpp.s
.PHONY : main.cpp.s

networkaccessmanagerfactory.o: networkaccessmanagerfactory.cpp.o

.PHONY : networkaccessmanagerfactory.o

# target to build an object file
networkaccessmanagerfactory.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/networkaccessmanagerfactory.cpp.o
.PHONY : networkaccessmanagerfactory.cpp.o

networkaccessmanagerfactory.i: networkaccessmanagerfactory.cpp.i

.PHONY : networkaccessmanagerfactory.i

# target to preprocess a source file
networkaccessmanagerfactory.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/networkaccessmanagerfactory.cpp.i
.PHONY : networkaccessmanagerfactory.cpp.i

networkaccessmanagerfactory.s: networkaccessmanagerfactory.cpp.s

.PHONY : networkaccessmanagerfactory.s

# target to generate assembly for a file
networkaccessmanagerfactory.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/networkaccessmanagerfactory.cpp.s
.PHONY : networkaccessmanagerfactory.cpp.s

powersaveblocker.o: powersaveblocker.cpp.o

.PHONY : powersaveblocker.o

# target to build an object file
powersaveblocker.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/powersaveblocker.cpp.o
.PHONY : powersaveblocker.cpp.o

powersaveblocker.i: powersaveblocker.cpp.i

.PHONY : powersaveblocker.i

# target to preprocess a source file
powersaveblocker.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/powersaveblocker.cpp.i
.PHONY : powersaveblocker.cpp.i

powersaveblocker.s: powersaveblocker.cpp.s

.PHONY : powersaveblocker.s

# target to generate assembly for a file
powersaveblocker.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/powersaveblocker.cpp.s
.PHONY : powersaveblocker.cpp.s

rpi-imager_autogen/EWIEGA46WW/qrc_qml.o: rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.o

.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_qml.o

# target to build an object file
rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.o
.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.o

rpi-imager_autogen/EWIEGA46WW/qrc_qml.i: rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.i

.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_qml.i

# target to preprocess a source file
rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.i
.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.i

rpi-imager_autogen/EWIEGA46WW/qrc_qml.s: rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.s

.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_qml.s

# target to generate assembly for a file
rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.s
.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_qml.cpp.s

rpi-imager_autogen/EWIEGA46WW/qrc_translations.o: rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.o

.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_translations.o

# target to build an object file
rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.o
.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.o

rpi-imager_autogen/EWIEGA46WW/qrc_translations.i: rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.i

.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_translations.i

# target to preprocess a source file
rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.i
.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.i

rpi-imager_autogen/EWIEGA46WW/qrc_translations.s: rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.s

.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_translations.s

# target to generate assembly for a file
rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.s
.PHONY : rpi-imager_autogen/EWIEGA46WW/qrc_translations.cpp.s

rpi-imager_autogen/mocs_compilation.o: rpi-imager_autogen/mocs_compilation.cpp.o

.PHONY : rpi-imager_autogen/mocs_compilation.o

# target to build an object file
rpi-imager_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/mocs_compilation.cpp.o
.PHONY : rpi-imager_autogen/mocs_compilation.cpp.o

rpi-imager_autogen/mocs_compilation.i: rpi-imager_autogen/mocs_compilation.cpp.i

.PHONY : rpi-imager_autogen/mocs_compilation.i

# target to preprocess a source file
rpi-imager_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/mocs_compilation.cpp.i
.PHONY : rpi-imager_autogen/mocs_compilation.cpp.i

rpi-imager_autogen/mocs_compilation.s: rpi-imager_autogen/mocs_compilation.cpp.s

.PHONY : rpi-imager_autogen/mocs_compilation.s

# target to generate assembly for a file
rpi-imager_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/rpi-imager.dir/build.make CMakeFiles/rpi-imager.dir/rpi-imager_autogen/mocs_compilation.cpp.s
.PHONY : rpi-imager_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rpi-imager"
	@echo "... rpi-imager_autogen"
	@echo "... acceleratedcryptographichash.o"
	@echo "... acceleratedcryptographichash.i"
	@echo "... acceleratedcryptographichash.s"
	@echo "... dependencies/mountutils/src/linux/functions.o"
	@echo "... dependencies/mountutils/src/linux/functions.i"
	@echo "... dependencies/mountutils/src/linux/functions.s"
	@echo "... dependencies/sha256crypt/sha256crypt.o"
	@echo "... dependencies/sha256crypt/sha256crypt.i"
	@echo "... dependencies/sha256crypt/sha256crypt.s"
	@echo "... downloadextractthread.o"
	@echo "... downloadextractthread.i"
	@echo "... downloadextractthread.s"
	@echo "... downloadstatstelemetry.o"
	@echo "... downloadstatstelemetry.i"
	@echo "... downloadstatstelemetry.s"
	@echo "... downloadthread.o"
	@echo "... downloadthread.i"
	@echo "... downloadthread.s"
	@echo "... driveformatthread.o"
	@echo "... driveformatthread.i"
	@echo "... driveformatthread.s"
	@echo "... drivelistitem.o"
	@echo "... drivelistitem.i"
	@echo "... drivelistitem.s"
	@echo "... drivelistmodel.o"
	@echo "... drivelistmodel.i"
	@echo "... drivelistmodel.s"
	@echo "... drivelistmodelpollthread.o"
	@echo "... drivelistmodelpollthread.i"
	@echo "... drivelistmodelpollthread.s"
	@echo "... imagewriter.o"
	@echo "... imagewriter.i"
	@echo "... imagewriter.s"
	@echo "... linux/linuxdrivelist.o"
	@echo "... linux/linuxdrivelist.i"
	@echo "... linux/linuxdrivelist.s"
	@echo "... linux/udisks2api.o"
	@echo "... linux/udisks2api.i"
	@echo "... linux/udisks2api.s"
	@echo "... localfileextractthread.o"
	@echo "... localfileextractthread.i"
	@echo "... localfileextractthread.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... networkaccessmanagerfactory.o"
	@echo "... networkaccessmanagerfactory.i"
	@echo "... networkaccessmanagerfactory.s"
	@echo "... powersaveblocker.o"
	@echo "... powersaveblocker.i"
	@echo "... powersaveblocker.s"
	@echo "... rpi-imager_autogen/EWIEGA46WW/qrc_qml.o"
	@echo "... rpi-imager_autogen/EWIEGA46WW/qrc_qml.i"
	@echo "... rpi-imager_autogen/EWIEGA46WW/qrc_qml.s"
	@echo "... rpi-imager_autogen/EWIEGA46WW/qrc_translations.o"
	@echo "... rpi-imager_autogen/EWIEGA46WW/qrc_translations.i"
	@echo "... rpi-imager_autogen/EWIEGA46WW/qrc_translations.s"
	@echo "... rpi-imager_autogen/mocs_compilation.o"
	@echo "... rpi-imager_autogen/mocs_compilation.i"
	@echo "... rpi-imager_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

