name: Feature Request
description: What would you like to see from rpi-imager?
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-could-be-better
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A description of the issue you're facing that requires this feature.
      placeholder: Ex. I never notice when OS writing has finished...
    validations:
      required: true
  - type: textarea
    id: what-do-you-want-to-see
    attributes:
      label: Describe the solution you would like to see implemented
      description: A clear and concise description of what you want to happen.
      placeholder: Ex. rpi-imager should initiate a confetti shower when writing is finished
    validations:
      required: true
  - type: textarea
    id: what-else-did-you-consider
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Ex. Alert sirens, SMS notifications, hiring a sky writer
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Ex. Must be large confetti to make it easier to clean up
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software did you last run?
      options:
        - 1.8.5 (Default)
        - 1.8.4
        - 1.8.3
        - 1.8.2
        - 1.8.1
        - < 1.8.0
      default: 0
    validations:
      required: true
